### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by svnwell** [xuthus5/fedora-netease#1]
netease-cloud-music: relocation error: /usr/bin/../lib/netease-cloud-music/lib/libqcef.so.1: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc version Qt_5 not defined in file libQt5Qml.so.5 with link time reference

**Comment by xuthus5** [comment]
发行版本号和环境是啥

**Comment by svnwell** [comment]
> 发行版本号和环境是啥

Linux localhost.localdomain 4.20.8-200.fc29.x86_64

**Comment by xuthus5** [comment]
桌面呢？你是否有安装过此类移植软件

**Comment by svnwell** [comment]
桌面 gnome，没有装过移植软件

**Comment by xuthus5** [comment]
我这里无法复现。你看看这篇博客是否可以帮你。https://blog.csdn.net/xiaohaozi911/article/details/82804753

**Comment by svnwell** [comment]
> 我这里无法复现。你看看这篇博客是否可以帮你。https://blog.csdn.net/xiaohaozi911/article/details/82804753

非常感谢，问题已解决，是动态库Qt5Qml版本不兼容导致的。 网易云音乐使用的版本是libQt5Qml.so.5.9.2; 我系统中的版本是libQt5Qml.5.11.3; 我在$LD_LIBRARY_PATH 的头部追加了网易云音乐中动态库的libQt5Qml的地址（/usr/lib64/netease-cloud-music/lib）后，程序正常启动，目前测试可用。 @xuthus5 建议在install.sh 中增加 “将网易云音乐动态库目录添加到环境变量 LD_LIBRARY_PATH”的操作。
